---
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_macOS-64bit.tar.gz
- sudo dpkg - i hugo* . deb

script:
- hugo

deploy:
- provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master